modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/Blackout03/No-Falling-Blocks/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/no-falling-blocks"
license="All rights reserved"

[[mods]]
modId="nofallingblocks"
version="${file.jarVersion}"
displayName="No Falling Blocks"
authors="Blackout"
description='''Ever get sick of all your blocks falling when you break a block. This mod fixes that for Vanilla Blocks and some Modded Blocks.'''
itemIcon="minecraft:sand"

[[dependencies.nofallingblocks]]
modId="forge"
mandatory=true
versionRange="[44.1.23,)"
ordering="NONE"
side="BOTH"

[[dependencies.nofallingblocks]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3]"
ordering="NONE"
side="BOTH"
